### ISSUE TITLE
spectral_norm_update_ops unused?

### ISSUE THREAD

**Issue by nwestlake** [google/compare_gan#12]
My understanding is that spectral_norm_update_ops in [compare_gan/src/gans/ops.py](https://github.com/google/compare_gan/blob/master/compare_gan/src/gans/ops.py) is not used at all and perhaps wasn't used.  Is my understanding correct?

**Comment by xiaohuazhai** [comment]
Thanks Nicholas, The spectral norm function is actually called via "def spectral_norm(input_)", in the operation linear and conv2d. 
https://github.com/google/compare_gan/blob/560697ee213f91048c6b4231ab79fcdd9bf20381/compare_gan/src/gans/ops.py#L63

The function spectral_norm_update_ops is deprecated and we will remove the unused code in the future release.
