### ISSUE TITLE
windows compitability error in gilbo.py

### ISSUE THREAD

**Issue by eyaler** [google/compare_gan#14]
in gilbo.py change:

outdir = os.path.join(outdir, checkpoint_path.replace('/', '_'))

to

outdir = os.path.join(outdir, checkpoint_path.replace('/', '_').replace('\\', '_'))

**Comment by Marvin182** [comment]
Thank you. I think GILBO does not work in the new version. If you send a pull request for v2 I can merge it.
To support GILBO in the new version please contact Ian Fischer.

Why do you change "_" to ""?
