### ISSUE TITLE
_model_fn() not implemented

### ISSUE THREAD

**Issue by hmeine** [google/compare_gan#17]
I tried instantiating a simple WGAN_CP (based on your task 3), but got this error:

    NotImplementedError: _model_fn() must be implemented in subclasses of AbstractGAN.

Looking at the code, there's only one file (`compare_gan/src/gans/gans_with_penalty.py`) which implements this function. I wonder how this worked for you – is this related to TF version or so?

I uploaded a gist with a testcase: https://gist.github.com/hmeine/d7ef0c38790dc885f3f73e621e14ff31
There's a button opening the notebook on colab, where you can see that the dependency versions are:

    tensor2tensor                      1.11.0               
    tensorflow                         1.13.0rc1

**Comment by Marvin182** [comment]
Please use train() instead of train_with_estimator(). The later is not
supported for all GAN classes. We will fix this with a release soon.

**Comment by hmeine** [comment]
Thanks, that helped indeed!

Just to give you some feedback: I like your repository a lot because it comprises so many different models and model configurations, but the purpose you developed it for shines through in the code structure and API – it is not very easy to use the code without setting up a full experiment the way you indended to use it.

**Comment by Marvin182** [comment]
Thank you for the feedback. I are working on a new release that focuses
more on single runs.

Hans Meine <notifications@github.com> schrieb am Do., 21. Feb. 2019, 00:04:
