### ISSUE TITLE
tensor2tensor not found!

### ISSUE THREAD

**Issue by Jiajie-Mei** [google/compare_gan#2]
Hello, when I run ”bash compare_gan_prepare_datasets.sh“， I got the error "tensor2tensor not found!". Clearly, there does not exist anything called t2t-datagen in the folder $HOME/.local/bin. So how can I get this file?

**Comment by cyfra** [comment]
Hey,

you have to install tensor2tensor package (for example using pip).

More detailed instructions are here:
https://github.com/tensorflow/tensor2tensor/blob/master/README.md

**Comment by Jiajie-Mei** [comment]
Thanks very much! I just ignored the content of the setup.py. Sorry to trouble you!
