### ISSUE TITLE
ssgan

### ISSUE THREAD

**Issue by jilner** [google/compare_gan#23]
thankyou very much fou your good job
I have some questions in ssgan,  where is the  discrimitor used in ssgan,and where is the loss used?
thanks again

**Comment by mariolucic** [comment]
Hi Jilner. ssgan.py defines the create_loss() method where the loss is specified. The discriminator and generator architectures are configured via Gin for the super-class (ModularGAN).

**Comment by jilner** [comment]
> Hi Jilner. ssgan.py defines the create_loss() method where the loss is specified. The discriminator and generator architectures are configured via Gin for the super-class (ModularGAN).

thanks for reply,  how can I run a ssgan model?
