### ISSUE TITLE
Triangle dataset

### ISSUE THREAD

**Issue by aaronrmm** [google/compare_gan#25]
Is there a place I can access the triangle data set mentioned in the paper, or it's generator anywhere? Thanks

**Comment by Marvin182** [comment]
Currently neither data or code are published. We are looking into options to publish it.

**Comment by mariolucic** [comment]
Hi aaronrmm, 
here is the colab to generate the data: https://colab.sandbox.google.com/github/google/compare_gan/blob/master/colabs/Convex_Polygons_Dataset.ipynb
