### ISSUE TITLE
Biggan expects whole integer as a label rather than a tensor

### ISSUE THREAD

**Issue by CrackerHax** [google/compare_gan#29]
Seems that  biggan can only be used unconditionally. This might be the case for infogan too. As far as I can tell, compare_gan does not make use of labels at all.

Here is my parse function:
```
  def parse_function(self, proto):
        feature_map = tf.parse_single_example(
            proto,
            features = {'image': tf.FixedLenFeature([], tf.string),
                        'label': tf.FixedLenSequenceFeature([NUM_CLASSES], tf.int64, allow_missing=1, default_value=[0])
            }
            )

        image = tf.decode_raw(feature_map['image'], tf.uint8)
        image = tf.reshape(image, (IMAGE_SIZE,IMAGE_SIZE,3))
        image = tf.cast(image, tf.float32) / 255.0

        label = feature_map['label']
        label = tf.cast(label, tf.int32)
        label = tf.reshape(label, (-1,NUM_CLASSES))

        return image, label
```

This starts throwing errors when the layers are being set up. It will only work if I return label as an integer (not a tensor).

**Comment by Marvin182** [comment]
If you are doing one-class classification then you can pass around the label ID (scalar) instead of vector. ModularGAN._get_one_hot_labels will then encode the label into a one hot encoded vector.
