### ISSUE TITLE
ssgan_128x128 model does not appear to be available

### ISSUE THREAD

**Issue by 16A0** [google/compare_gan#33]
Hello TF team!  Greatly appreciate the work, robust documentation, and examples.  THANK YOU inadvance!

I think the bug I've identified is related to either:

- my set up on a Mac; or
- a model not yet being on TFHub.

=======
Running:
=======
tensorboard          1.13.1   
tensorflow           1.13.1   
tensorflow-estimator 1.13.0   
tensorflow-hub       0.5.0 

===================
Attempting to load model:
===================
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

import IPython
from IPython.display import display
import numpy as np
import PIL.Image
import pandas as pd
import six
import tensorflow as tf
import tensorflow_hub as hub

def imgrid(imarray, cols=8, pad=1):
  pad = int(pad)
  assert pad >= 0
  cols = int(cols)
  assert cols >= 1
  N, H, W, C = imarray.shape
  rows = int(np.ceil(N / float(cols)))
  batch_pad = rows * cols - N
  assert batch_pad >= 0
  post_pad = [batch_pad, pad, pad, 0]
  pad_arg = [[0, p] for p in post_pad]
  imarray = np.pad(imarray, pad_arg, 'constant')
  H += pad
  W += pad
  grid = (imarray
          .reshape(rows, cols, H, W, C)
          .transpose(0, 2, 1, 3, 4)
          .reshape(rows*H, cols*W, C))
  return grid[:-pad, :-pad]

def imshow(a, format='png', jpeg_fallback=True):
  a = np.asarray(a, dtype=np.uint8)
  if six.PY3:
    str_file = six.BytesIO()
  else:
    str_file = six.StringIO()
  PIL.Image.fromarray(a).save(str_file, format)
  png_data = str_file.getvalue()
  try:
    disp = display(IPython.display.Image(png_data))
  except IOError:
    if jpeg_fallback and format != 'jpeg':
      print ('Warning: image was too large to display in format "{}"; '
             'trying jpeg instead.').format(format)
      return imshow(a, format='jpeg')
    else:
      raise
  return disp

class Generator(object):

  def __init__(self, module_spec):
    self._module_spec = module_spec
    self._sess = None
    self._graph = tf.Graph()
    self._load_model()

  @property
  def z_dim(self):
    return self._z.shape[-1].value

  @property
  def conditional(self):
    return self._labels is not None

  def _load_model(self):
    with self._graph.as_default():
      self._generator = hub.Module(self._module_spec, name="gen_module",
                                   tags={"gen", "bsNone"})
      input_info = self._generator.get_input_info_dict()
      inputs = {k: tf.placeholder(v.dtype, v.get_shape().as_list(), k)
                for k, v in self._generator.get_input_info_dict().items()}
      self._samples = self._generator(inputs=inputs, as_dict=True)["generated"]
      print("Inputs:", inputs)
      print("Outputs:", self._samples)
      self._z = inputs["z"]
      self._labels = inputs.get("labels", None)

  def _init_session(self):
    if self._sess is None:
      self._sess = tf.Session(graph=self._graph)
      self._sess.run(tf.global_variables_initializer())

  def get_noise(self, num_samples, seed=None):
    if np.isscalar(seed):
      np.random.seed(seed)
      return np.random.normal(size=[num_samples, self.z_dim])
    z = np.empty(shape=(len(seed), self.z_dim), dtype=np.float32)
    for i, s in enumerate(seed):
      np.random.seed(s)
      z[i] = np.random.normal(size=[self.z_dim])
    return z

  def get_samples(self, z, labels=None):
    with self._graph.as_default():
      self._init_session()
      feed_dict = {self._z: z}
      if self.conditional:
        assert labels is not None
        assert labels.shape[0] == z.shape[0]
        feed_dict[self._labels] = labels
      samples = self._sess.run(self._samples, feed_dict=feed_dict)
      return np.uint8(np.clip(256 * samples, 0, 255))

class Discriminator(object):

  def __init__(self, module_spec):
    self._module_spec = module_spec
    self._sess = None
    self._graph = tf.Graph()
    self._load_model()

  @property
  def conditional(self):
    return "labels" in self._inputs

  @property
  def image_shape(self):
    return self._inputs["images"].shape.as_list()[1:]

  def _load_model(self):
    with self._graph.as_default():
      self._discriminator = hub.Module(self._module_spec, name="disc_module",
                                       tags={"disc", "bsNone"})
      input_info = self._discriminator.get_input_info_dict()
      self._inputs = {k: tf.placeholder(v.dtype, v.get_shape().as_list(), k)
                      for k, v in input_info.items()}
      self._outputs = self._discriminator(inputs=self._inputs, as_dict=True)
      print("Inputs:", self._inputs)
      print("Outputs:", self._outputs)

  def _init_session(self):
    if self._sess is None:
      self._sess = tf.Session(graph=self._graph)
      self._sess.run(tf.global_variables_initializer())

  def predict(self, images, labels=None):
    with self._graph.as_default():
      self._init_session()
      feed_dict = {self._inputs["images"]: images}
      if "labels" in self._inputs:
        assert labels is not None
        assert labels.shape[0] == images.shape[0]
        feed_dict[self._inputs["labels"]] = labels
      return self._sess.run(self._outputs, feed_dict=feed_dict)

# @title Load Model

model_name = "SSGAN 128x128 (FID 20.6, IS 24.9)"
models = {
    "SSGAN 128x128": "https://tfhub.dev/google/compare_gan/ssgan_128x128/1",
}

======
Output:
======
Module spec: https://tfhub.dev/google/compare_gan/ssgan_128x128/1
Loading model...
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-3-e8296512043f> in <module>
     11 tf.reset_default_graph()
     12 print("Loading model...")
---> 13 sampler = Generator(module_spec)
     14 print("Model loaded.")

<ipython-input-2-f030bee597ef> in __init__(self, module_spec)
     64     self._sess = None
     65     self._graph = tf.Graph()
---> 66     self._load_model()
     67 
     68   @property

<ipython-input-2-f030bee597ef> in _load_model(self)
     77     with self._graph.as_default():
     78       self._generator = hub.Module(self._module_spec, name="gen_module",
---> 79                                    tags={"gen", "bsNone"})
     80       input_info = self._generator.get_input_info_dict()
     81       inputs = {k: tf.placeholder(v.dtype, v.get_shape().as_list(), k)

~/anaconda3/envs/base_ml/lib/python3.7/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
    168           name=self._name,
    169           trainable=self._trainable,
--> 170           tags=self._tags)
    171       # pylint: enable=protected-access
    172 

~/anaconda3/envs/base_ml/lib/python3.7/site-packages/tensorflow_hub/native_module.py in _create_impl(self, name, trainable, tags)
    338         trainable=trainable,
    339         checkpoint_path=self._checkpoint_variables_path,
--> 340         name=name)
    341 
    342   def _export(self, path, variables_saver):

~/anaconda3/envs/base_ml/lib/python3.7/site-packages/tensorflow_hub/native_module.py in __init__(self, spec, meta_graph, trainable, checkpoint_path, name)
    380 
    381     register_ops_if_needed({
--> 382         op.name for op in self._meta_graph.meta_info_def.stripped_op_list.op})
    383 
    384     if _is_tpu_graph_function():

~/anaconda3/envs/base_ml/lib/python3.7/site-packages/tensorflow_hub/native_module.py in register_ops_if_needed(graph_ops)
    820         "Graph ops missing from the python registry (%s) are also absent from "
    821         "the c++ registry."
--> 822         % missing_ops.difference(set(cpp_registry_ops.keys())))
    823 
    824 

NotFoundError: Graph ops missing from the python registry ({'BatchMatMulV2'}) are also absent from the c++ registry.

**Comment by Marvin182** [comment]
I can confirm that the model is still available on TFHub.
Running the (https://colab.research.google.com/github/google/compare_gan/blob/v3/colabs/ssgan_demo.ipynb)[Colab] works for me.

The error looks very much like incompatible versions. Can you try to update TF and TFHub. to me the tfhub version looks quite new, but TF 1.13 is relatively old.
If that doesn't work please contact the TFHub team.

**Comment by RuiLiFeng** [comment]
I've also found that SSGAN is not available on tfhub.dev. I search "SSGAN" directly on the website, and the result is empty.
![image](https://user-images.githubusercontent.com/33709183/66638544-b9781a80-ec47-11e9-863b-ecba36a0c46e.png)
![image](https://user-images.githubusercontent.com/33709183/66638559-c1d05580-ec47-11e9-9da2-6cc032e4dd33.png)
