### ISSUE TITLE
train on GPU

### ISSUE THREAD

**Issue by littlealili** [google/compare_gan#38]
Hello, if I want to run training on the GPU, how should I modify the program?

**Comment by RuiLiFeng** [comment]
If you only want to run on a  single GPU, then no change is needed.

If you want to run on multi-gpus, then you may need to define your own training_loop, as tf.estimator is not supported well for multi-gpu training.

**Comment by leekyungmoon** [comment]
After changing **TPU-related codes** (e.g., `"tf.contrib.tpu.RunConfig"`, `"tf.contrib.tpu.TPUEstimator"` and `"tf.contrib.tpu.TPUEstimatorSpec"`)  to **GPU-related codes** (e.g., `"tf.estimator.RunConfig"`, `"tf.estimator.Estimator"` and `"tf.estimator.EstimatorSpec"`) and  adding the API for the distributed training `"tf.distribute.MirroredStrategy"`, I got an error stated below:

> ValueError: You must specify an aggregation method to update a MirroredVariable in Replica Context. You can do so by passing an explicit value for argument `aggregation` to tf.Variable(..).e.g. `tf.Variable(..., aggregation=tf.VariableAggregation.SUM)``tf.VariableAggregation` lists the possible aggregation methods.This is required because MirroredVariable should always be kept in sync. When updating them or assigning to them in a replica context, we automatically try to aggregate the values before updating the variable. For this aggregation, we need to know the aggregation method. Another alternative is to not try to update such MirroredVariable in replica context, but in cross replica context. You can enter cross replica context by calling `tf.distribute.get_replica_context().merge_call(merge_fn, ..)`.Inside `merge_fn`, you can then update the MirroredVariable using `tf.distribute.StrategyExtended.update()`.
> In call to configurable 'spectral_norm' (<function spectral_norm at 0x7f47c05b01e0>)

Is there any solution/comment for this?
Thanks in advance.
