### ISSUE TITLE
Problem about shuffle buffer size for unconditional GAN

### ISSUE THREAD

**Issue by RuiLiFeng** [google/compare_gan#40]
I notice that the shuffle buffer size is 10000, and is not included in gin configurations. While the original imagenet datasets are sorted by classes, this means that the images are feeded to the unconditional GANs with class info. Could that contradicts the unconditional training, especially for SSGAN and S3GAN?

**Comment by Marvin182** [comment]
TensorFlow Datasets does not store images in original order.
