### ISSUE TITLE
should change setup.py

### ISSUE THREAD

**Issue by daiwk** [google/compare_gan#6]
should change

`    scripts=[
        'bin/compare_gan_generate_tasks',
        'bin/compare_gan_prepare_datasets.sh',
        'bin/compare_gan_run_one_task',
        'bin/compare_gan_run_test.sh',
    ],  `
to
`    scripts=[
        'compare_gan/bin/compare_gan_generate_tasks',
        'compare_gan/bin/compare_gan_prepare_datasets.sh',
        'compare_gan/bin/compare_gan_run_one_task',
        'compare_gan/bin/compare_gan_run_test.sh',
    ],  `

**Comment by xiaohuazhai** [comment]
Thanks a lot for reporting this issue. We have fixed the paths in setup.py.
