### ISSUE TITLE
WGAN gradient penalty coupled with spectral normalization，generator and discriminator loss are both  nan

### ISSUE THREAD

**Issue by IPNUISTlegal** [google/compare_gan#9]
gradient penalty coupled with spectral normalization ,two (generator and discriminator) loss are nan.
cancel gradient penalty  and  just use spectral normalization in Ex∼qdata[D(x)]−Ez∼p(z)[D(G(z))]，two (generator and discriminator) loss are normal.
why？cause  i am a noob in deeplearning.
thx!

**Comment by chentingpc** [comment]
Should be fine using both gp and sn for discriminator, and it may work better than just sn.

**Comment by IPNUISTlegal** [comment]
I use wrong sn code, just use google sn code,it's fine.

**Comment by IPNUISTlegal** [comment]
@chentingpc Sorry bother your again. Spectral_norm function in the code performs Spectral Normalization on a weight tensor. Authors use it on convolution. I wonder whether spectral_norm function code can apply to deconvolution. But, the shape of w in convolution is https://github.com/google/compare_gan/blob/cb8dee9e7615f6ba7a32471a13007a98edb1b2ca/compare_gan/src/gans/ops.py#L182
the shape of w in deconvolution is https://github.com/google/compare_gan/blob/cb8dee9e7615f6ba7a32471a13007a98edb1b2ca/compare_gan/src/gans/ops.py#L198
It's fine to directly use spectral_norm(w) in deconvolution just the same way in convolution?
thx a lot

**Comment by chentingpc** [comment]
it is fine, power iteration of both converges to the same largest singular value of  A. may save some small compute if done power iteration is put on the smaller dimensions.
